<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'name' => 'Air Terjun Tangse',
                'province' => 'Aceh',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Air terjun tersembunyi di hutan Pidie dengan air yang sangat dingin dan jernih.',
                'vibe_description' => 'Jauh dari kebisingan kota, suara gemuruh air yang jatuh di antara tebing batu menciptakan orkestra alam yang menenangkan.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Area Parkir', 'Warung Kecil'],
                'contact_person' => '628110000001',
                'cover_image' => 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Situmurun',
                'province' => 'Sumatera Utara',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 50000,
                'description' => 'Air terjun unik yang alirannya langsung jatuh ke Danau Toba.',
                'vibe_description' => 'Melihat air terjun dari atas kapal di tengah danau vulkanik terbesar adalah pengalaman magis.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Sewa Kapal', 'Spot Foto'],
                'contact_person' => '628110000002',
                'cover_image' => 'https://images.unsplash.com/photo-1546484488-2a1430996887?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Lubuak Rantiang',
                'province' => 'Sumatera Barat',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Kolam alami berwarna hijau toska di tengah hutan rimbun Padang.',
                'vibe_description' => 'Seperti menemukan kolam rahasia para peri. Airnya tenang dan dingin.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Area Parkir', 'Kamar Bilas'],
                'contact_person' => '628110000003',
                'cover_image' => 'https://images.unsplash.com/photo-1596395818817-db3e945a2d48?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Batang Kapas',
                'province' => 'Riau',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 25000,
                'description' => 'Air terjun tertinggi di Sumatera bagian tengah, tersembunyi jauh di pedalaman.',
                'vibe_description' => 'Kemegahan dinding batu raksasa dengan air yang jatuh dari ketinggian 150 meter.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Area Camping', 'Pos Pendakian'],
                'contact_person' => '628110000004',
                'cover_image' => 'https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Biru Bintan',
                'province' => 'Kepulauan Riau',
                'nature_type' => 'Danau',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 10000,
                'description' => 'Danau bekas galian yang berubah menjadi oasis biru cerah.',
                'vibe_description' => 'Kontras warna biru air dan putih pasirnya memanjakan mata.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Warung Kelapa Muda', 'Toilet'],
                'contact_person' => '628110000005',
                'cover_image' => 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Kaco',
                'province' => 'Jambi',
                'nature_type' => 'Danau',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 15000,
                'description' => 'Danau kecil di tengah hutan Kerinci dengan air sebening kaca.',
                'vibe_description' => 'Kesunyian hutan hujan tropis memeluk erat tempat ini.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Pos Jaga', 'Area Camping'],
                'contact_person' => '628110000006',
                'cover_image' => 'https://images.unsplash.com/photo-1629255877395-816790588665?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pulau Tikus',
                'province' => 'Bengkulu',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 150000,
                'description' => 'Pulau karang kecil tak berpenghuni dengan air jernih.',
                'vibe_description' => 'Pulau pribadi untuk sehari. Hanya ada suara ombak dan burung laut.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Mercusuar', 'Spot Snorkeling'],
                'contact_person' => '628110000007',
                'cover_image' => 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Ranau',
                'province' => 'Sumatera Selatan',
                'nature_type' => 'Danau',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 20000,
                'description' => 'Danau terbesar kedua di Sumatera dengan latar Gunung Seminung.',
                'vibe_description' => 'Udara sejuk pegunungan bercampur dengan ketenangan air danau.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Penginapan', 'Pemandian Air Panas'],
                'contact_person' => '628110000008',
                'cover_image' => 'https://images.unsplash.com/photo-1627392873775-68426cb78715?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pantai Aik Antu',
                'province' => 'Kepulauan Bangka Belitung',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Pantai tersembunyi dengan bebatuan granit raksasa.',
                'vibe_description' => 'Sunyi dan magis. Batuan granit purba seolah menjadi penjaga abadi.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Toilet', 'Warung Sederhana'],
                'contact_person' => '628110000009',
                'cover_image' => 'https://images.unsplash.com/photo-1543360253-33318f77259c?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Teluk Kiluan',
                'province' => 'Lampung',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sedang',
                'price_estimate' => 35000,
                'description' => 'Teluk alami tempat lumba-lumba hidung botol berenang bebas.',
                'vibe_description' => 'Melihat lumba-lumba melompat bebas di habitat aslinya memberikan rasa haru.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Homestay', 'Sewa Jukung'],
                'contact_person' => '628110000010',
                'cover_image' => 'https://images.unsplash.com/photo-1568289874-90a421b9204f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pulau Sangiang',
                'province' => 'Banten',
                'nature_type' => 'Hutan',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 200000,
                'description' => 'Pulau konservasi dengan hutan bakau lebat dan pantai perawan.',
                'vibe_description' => 'Menjelajah hutan bakau dengan perahu kano saat matahari terbenam.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Pos Ranger', 'Area Camping'],
                'contact_person' => '628120000001',
                'cover_image' => 'https://images.unsplash.com/photo-1619266465172-02a857c3556d?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pulau Cipir',
                'province' => 'DKI Jakarta',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 15000,
                'description' => 'Pulau bersejarah di Kepulauan Seribu dengan reruntuhan tua yang estetik.',
                'vibe_description' => 'Reruntuhan bangunan kolonial yang diambil alih oleh akar pohon memberikan nuansa hening.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Dermaga', 'Toilet'],
                'contact_person' => '628120000002',
                'cover_image' => 'https://images.unsplash.com/photo-1544644181-1bc6a7605d8b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Sanghyang Heuleut',
                'province' => 'Jawa Barat',
                'nature_type' => 'Danau',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 20000,
                'description' => 'Laguna purba dengan air kehijauan di antara tebing batu putih.',
                'vibe_description' => 'Berenang di sini terasa seperti kembali ke zaman prasejarah.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Penyewaan Pelampung', 'Warung'],
                'contact_person' => '628120000003',
                'cover_image' => 'https://images.unsplash.com/photo-1647241315629-b4728dd301c3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Hutan Pinus Limpakuwus',
                'province' => 'Jawa Tengah',
                'nature_type' => 'Hutan',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 15000,
                'description' => 'Hutan pinus di lereng Gunung Slamet yang sering diselimuti kabut.',
                'vibe_description' => 'Udara dingin dan aroma getah pinus yang khas langsung menenangkan saraf.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Toilet', 'Mushola', 'Area Camping'],
                'contact_person' => '628120000004',
                'cover_image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Randusari',
                'province' => 'DI Yogyakarta',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Air terjun kembar yang tersembunyi di dalam rimbunnya kebun warga.',
                'vibe_description' => 'Suara gemericik air yang konstan dan keteduhan pohon bambu.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Parkir Warga', 'Gazebo'],
                'contact_person' => '628120000005',
                'cover_image' => 'https://images.unsplash.com/photo-1546949392-15f94d075727?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Ranu Regulo',
                'province' => 'Jawa Timur',
                'nature_type' => 'Danau',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 19000,
                'description' => 'Danau sunyi di kaki Gunung Semeru yang menawarkan kabut pagi magis.',
                'vibe_description' => 'Hening yang absolut. Hanya ada kabut yang menari di atas permukaan air.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Area Camping', 'Warung'],
                'contact_person' => '628120000006',
                'cover_image' => 'https://images.unsplash.com/photo-1616489953149-74d3202e2102?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pantai Geger',
                'province' => 'Bali',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 10000,
                'description' => 'Sudut tersembunyi di Nusa Dua dengan pasir putih lembut.',
                'vibe_description' => 'Sisi lain Bali yang hening. Jauh dari keramaian beach club.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Sewa Kursi Jemur', 'Cafe Kecil'],
                'contact_person' => '628130000001',
                'cover_image' => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pantai Kecinan',
                'province' => 'Nusa Tenggara Barat',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Pantai di Lombok Utara dengan pohon kelapa yang instagramable.',
                'vibe_description' => 'Menonton sunset di sini tanpa gangguan siapapun adalah kemewahan.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Parkir Luas', 'Warung'],
                'contact_person' => '628130000002',
                'cover_image' => 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Ngabatata',
                'province' => 'Nusa Tenggara Timur',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Air terjun eksotis di Nagekeo yang dikelilingi padang savana.',
                'vibe_description' => 'Perpaduan suara air terjun dan desau angin di padang rumput savana.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Area Parkir Alami'],
                'contact_person' => '628130000003',
                'cover_image' => 'https://images.unsplash.com/photo-1682687982501-1e58ab814714?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pulau Randayan',
                'province' => 'Kalimantan Barat',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 50000,
                'description' => 'Pulau kecil dengan kekayaan bawah laut yang masih terjaga.',
                'vibe_description' => 'Duduk di dermaga kayu sambil melihat ikan-ikan kecil berenang di air jernih.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Villa', 'Dive Center'],
                'contact_person' => '628140000001',
                'cover_image' => 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Biru Tewang',
                'province' => 'Kalimantan Tengah',
                'nature_type' => 'Danau',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 10000,
                'description' => 'Danau air biru menyala di tengah hutan Katingan.',
                'vibe_description' => 'Warna biru airnya begitu kontras dengan hijaunya hutan Kalimantan.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Area Parkir', 'Spot Foto'],
                'contact_person' => '628140000002',
                'cover_image' => 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Bukit Sapu Angin',
                'province' => 'Kalimantan Selatan',
                'nature_type' => 'Pegunungan',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 10000,
                'description' => 'Bukit hijau dengan pemandangan 360 derajat ke arah pegunungan Meratus.',
                'vibe_description' => 'Angin sepoi-sepoi di puncak bukit ini akan meniup pergi segala kekhawatiran Anda.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Area Camping'],
                'contact_person' => '628140000003',
                'cover_image' => 'https://images.unsplash.com/photo-1632829285438-e4b2d4992569?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Labuan Cermin',
                'province' => 'Kalimantan Timur',
                'nature_type' => 'Danau',
                'crowd_level' => 'Sedang',
                'price_estimate' => 100000,
                'description' => 'Danau dua rasa (asin dan tawar) yang airnya sebening kristal.',
                'vibe_description' => 'Mengapung di atas perahu di sini rasanya seperti melayang di udara.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Sewa Perahu', 'Penyewaan Ban'],
                'contact_person' => '628140000004',
                'cover_image' => 'https://images.unsplash.com/photo-1621532822453-61b65e6389f4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Krayan',
                'province' => 'Kalimantan Utara',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 0,
                'description' => 'Air terjun perawan di perbatasan Indonesia-Malaysia.',
                'vibe_description' => 'Benar-benar definisi hidden gem. Hanya suara alam murni yang terdengar di sini.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Tidak Ada Fasilitas'],
                'contact_person' => '628140000005',
                'cover_image' => 'https://images.unsplash.com/photo-1445583934509-4152773b06c7?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pantai Pulisan',
                'province' => 'Sulawesi Utara',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 10000,
                'description' => 'Pantai pasir putih dengan gua-gua batuan eksotis di Likupang.',
                'vibe_description' => 'Pasir putih yang halus dan air laut tenang.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Homestay', 'Warung'],
                'contact_person' => '628150000001',
                'cover_image' => 'https://images.unsplash.com/photo-1519046904884-53103b34b271?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Botumoito',
                'province' => 'Gorontalo',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Air terjun bertingkat yang tersembunyi di hutan Boalemo.',
                'vibe_description' => 'Kesejukan air dan rimbunnya hutan tropis Gorontalo.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Area Parkir'],
                'contact_person' => '628150000002',
                'cover_image' => 'https://images.unsplash.com/photo-1473625247510-8ceb1760943f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Paisupok',
                'province' => 'Sulawesi Tengah',
                'nature_type' => 'Danau',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 15000,
                'description' => 'Danau sebening kaca di Banggai Kepulauan. Sering disebut danau cermin.',
                'vibe_description' => 'Mendayung perahu di sini seperti melayang. Keheningan dan kejernihan airnya terasa tidak nyata.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Sewa Perahu'],
                'contact_person' => '628150000003',
                'cover_image' => 'https://images.unsplash.com/photo-1594389953909-6449175d4a41?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Tamasapi',
                'province' => 'Sulawesi Barat',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 5000,
                'description' => 'Air terjun setinggi 75 meter di Mamuju yang dikelilingi pohon durian.',
                'vibe_description' => 'Gemuruh air yang jatuh dari ketinggian memberikan efek white noise alami.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Gazebo', 'Toilet'],
                'contact_person' => '628150000004',
                'cover_image' => 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Rammang-Rammang',
                'province' => 'Sulawesi Selatan',
                'nature_type' => 'Pegunungan',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 250000,
                'description' => 'Pegunungan karst terbesar kedua di dunia yang bisa disusuri dengan perahu.',
                'vibe_description' => 'Menyusuri sungai di antara tebing karst purba saat kabut turun.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Dermaga', 'Homestay'],
                'contact_person' => '628150000005',
                'cover_image' => 'https://images.unsplash.com/photo-1597084930107-160655c4860b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pulau Labengki',
                'province' => 'Sulawesi Tenggara',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sedang',
                'price_estimate' => 300000,
                'description' => 'Miniatur Raja Ampat dengan laguna biru berbentuk hati.',
                'vibe_description' => 'Keindahan laguna biru yang dikelilingi bukit karang tajam. Sepi, tenang.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Homestay', 'Jalur Trekking'],
                'contact_person' => '628150000006',
                'cover_image' => 'https://images.unsplash.com/photo-1588668214407-6ea9e6d8c278?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pantai Ora',
                'province' => 'Maluku',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 500000,
                'description' => 'Surga tersembunyi di Pulau Seram dengan resort di atas air.',
                'vibe_description' => 'Maldives-nya Indonesia. Bangun tidur langsung disambut ikan-ikan karang.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Resort', 'Dive Center'],
                'contact_person' => '628160000001',
                'cover_image' => 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pulau Sayafi',
                'province' => 'Maluku Utara',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 20000,
                'description' => 'Pulau kecil berpasir putih halus di Halmahera Tengah.',
                'vibe_description' => 'Pulau tak berpenghuni yang memberikan privasi total.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Tidak Ada Fasilitas'],
                'contact_person' => '628160000002',
                'cover_image' => 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Pantai Pasir Enam',
                'province' => 'Papua',
                'nature_type' => 'Pantai',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 20000,
                'description' => 'Pantai tersembunyi di Jayapura yang masih sangat alami.',
                'vibe_description' => 'Deburan ombak Pasifik yang kuat namun menenangkan.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Pondok Kayu'],
                'contact_person' => '628170000001',
                'cover_image' => 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Kiti Kiti',
                'province' => 'Papua Barat',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 50000,
                'description' => 'Air terjun unik di Fakfak yang alirannya langsung jatuh ke laut lepas.',
                'vibe_description' => 'Pemandangan langka di mana air tawar bertemu air asin.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Sewa Longboat'],
                'contact_person' => '628170000002',
                'cover_image' => 'https://images.unsplash.com/photo-1442183344697-b6771e8cc340?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Klasof',
                'province' => 'Papua Barat Daya',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 50000,
                'description' => 'Air terjun di pedalaman Sorong dengan air berwarna biru toska.',
                'vibe_description' => 'Trekking menembus hutan Papua terbayar lunas saat melihat kolam biru alami ini.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Pemandu Lokal'],
                'contact_person' => '628170000003',
                'cover_image' => 'https://images.unsplash.com/photo-1544837375-3453b532918e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Air Terjun Bihewa',
                'province' => 'Papua Tengah',
                'nature_type' => 'Air Terjun',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 20000,
                'description' => 'Air terjun bertingkat raksasa yang tersembunyi di hutan Nabire.',
                'vibe_description' => 'Kemegahan alam Papua terpancar di sini. Suara alamnya begitu dominan.',
                'access_difficulty' => 'Menantang',
                'facilities_list' => ['Area Parkir'],
                'contact_person' => '628170000004',
                'cover_image' => 'https://images.unsplash.com/photo-1533282247738-4e8979178f79?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Lembah Senyum',
                'province' => 'Papua Pegunungan',
                'nature_type' => 'Pegunungan',
                'crowd_level' => 'Cukup Sepi',
                'price_estimate' => 10000,
                'description' => 'Lembah hijau di Wamena yang konon membuat siapa saja yang datang akan tersenyum kagum.',
                'vibe_description' => 'Udara sejuk pegunungan tengah Papua dan keramahan alamnya memberikan kedamaian batin.',
                'access_difficulty' => 'Sedang',
                'facilities_list' => ['Spot Foto'],
                'contact_person' => '628170000005',
                'cover_image' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'name' => 'Danau Rawa Biru',
                'province' => 'Papua Selatan',
                'nature_type' => 'Danau',
                'crowd_level' => 'Sangat Sepi',
                'price_estimate' => 10000,
                'description' => 'Danau rawa yang menjadi sumber air Merauke, dikelilingi vegetasi unik.',
                'vibe_description' => 'Tenang dan datar. Memandang rawa luas ini memberikan perspektif baru.',
                'access_difficulty' => 'Mudah',
                'facilities_list' => ['Dermaga Kecil'],
                'contact_person' => '628170000006',
                'cover_image' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80',
            ],
        ];

        foreach ($destinations as $item) {
            $searchQuery = urlencode($item['name'] . ' ' . $item['province']);
            $validMapUrl = "https://maps.google.com/maps?q={$searchQuery}&t=&z=13&ie=UTF8&iwloc=&output=embed";

            Destination::firstOrCreate(
                ['slug' => Str::slug($item['name'])],
                [
                    'name' => $item['name'],
                    'province' => $item['province'],
                    'nature_type' => $item['nature_type'],
                    'crowd_level' => $item['crowd_level'],
                    'price_estimate' => $item['price_estimate'],
                    'description' => $item['description'],
                    'vibe_description' => $item['vibe_description'],
                    'access_difficulty' => $item['access_difficulty'],
                    'facilities_list' => $item['facilities_list'],
                    'location_url' => $validMapUrl, 
                    'contact_person' => $item['contact_person'],
                    'cover_image' => $item['cover_image'],
                ]
            );
        }
    }
}